const mongoose = require("mongoose");
const autoIncrement = require('mongoose-sequence')(mongoose);
const songsInfoScehma = new mongoose.Schema(
  {
    users_id:{ type: Number, require:true },
    AudioDocument: { type : [], default: ([]) },
    Trackversion: {type: String,
      required: true},
    Instrumental: {type: String,
      required: true},
    Title: {type: String,
      required: true},
    VersionSubtitle: {type: String,
      required: true},
    Primaryartist:{type: String,
      required: true},
    FeaturingArtist:{type: String,
      required: true},
    Author:{type: String,
      required: true},
    Composer:{type: String,
      required: true},
    Producer:{type: String,
      required: true},
    Publisher:{type: String,
      required: true},
    ISRC:{type: String,
      required: true},
    Genre:{type: String,
      required: true},
    Subgenre:{type: String,
      required: true},
    ExplicitVersion:{type: String,
      required: true},
    TrackTitleLanguage:{type: String,
      required: true},
    LyricsLanguage:{type: String,
      required: true},
    Lyrics:{type: String,
      required: true},
    CallerTuneTiming:{type: String,
      required: true},
    DistributeMusicvideo:{type: String,
      required: true},
    createdAt: { type : Date, default: Date.now }, 
    updatedAt: { type : Date, },
  },
  {
    collection: "songsInfo",
  }
);
songsInfoScehma.plugin(autoIncrement, {inc_field: 'songsInfo_id'});
module.exports= mongoose.model("songsInfo", songsInfoScehma);
